POST http://121.124.125.212:7500/sms/mo-report
Content-Type: application/json

{
  "msgVerId": 0,
  "encFlag": 0,
  "data": {
    "srcCallNo": "01048004512",
    "destCID": "1570501699",
    "msgCode": 11,
    "msgSubCode": 9,
    "msgId": "3B639FBF",
    "result": 0,
    "msgStatus" : 2
  }
}
###
/*MsgStatus (int) - 2:DELIVERED, 3:EXPIRED, 5:UNDELIVERED 등*/

