spring.application.name=SKT_GIPHTTP_MO
server.port=7500
#ThreadPool Setting true==ok
witcom.performance.loop=true
witcom.performance.cacheLoop=true
witcom.performance.per=1
witcom.performance.cLibFileName=JNALibrary.so
witcom.performance.cLibraryFilePath=/APP/sms/src_java/LIB/JNALibrary.so
witcom.performance.prometheus-url=http://localhost:8080/metrics
witcom.performance.cLibPath=/APP/sms/src_java/LIB
witcom.performance.valid-mobile-prefixes=010,011,016,017,018,019,012
witcom.performance.moduleName=GIPHTTP
witcom.performance.pFilePath=/log/BRTBV-SMSS-APP02/
witcom.performance.cFilePath=/log/BRTBV-SMSS-APP02/
#==================================================================================================#
# Altibase Database Config
#==================================================================================================#
#spring.datasource.driver-class-name=Altibase.jdbc.driver.AltibaseDriver
#spring.datasource.url=jdbc:Altibase://121.124.125.227:20301/sms
#spring.datasource.username=sms
#spring.datasource.password=sms97
#spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.dialect=com.infra.mo.skt_giphttp_mo.config.db.AltibaseDialect
#spring.jpa.properties.hibernate.dialect=com.altibase.hibernate.dialect.AltibaseDialect  # ??, ???
spring.datasource.altibase.jpa.driver-class-name=Altibase.jdbc.driver.AltibaseDriver
spring.datasource.altibase.jpa.url=jdbc:Altibase://172.1.72.104:20301/sms
spring.datasource.altibase.jpa.username=smsbd
spring.datasource.altibase.jpa.password=alTisktbd1213!
spring.datasource.altibase.jpa.encoding=UTF-16
spring.datasource.altibase.jpa.max-active=150
spring.datasource.altibase.jpa.max-idle=50
spring.datasource.altibase.jpa.min-idle=10
spring.datasource.altibase.jpa.max-wait=-1
spring.datasource.altibase.jpa.initial-size=10
spring.datasource.altibase.jpa.test-on-borrow=true
spring.datasource.altibase.jpa.test-while-idle=true
spring.datasource.altibase.jpa.validation-query=SELECT 1
spring.datasource.altibase.jpa.time-between-eviction-runs-millis=3000
spring.datasource.altibase.jpa.min-evictable-idle-time-millis=7200000
#==================================================================================================#
jwt.jwk-set-uri=http://60.30.143.32:8500/.well-known/jwks.json
jwt.issuer-uri=https://www.witcom.co.kr
jwt.key-id=witcom-gip-http-20250616
jwt.sub=witcom
jwt.expiredTimeSecond=31564779200
#==================================================================================================#
# \u00EB\u00A1\u009C\u00EA\u00B7\u00B8 \u00EB\u00A0\u0088\u00EB\u00B2\u00A8 \u00EC\u0084\u00A4\u00EC\u00A0\u0095
logging.level.root=DEBUG
logging.level.com.infra.recv.skt_giphttp_recv=DEBUG
logging.level.com.infra.recv.skt_giphttp_recv.config.application.WitcomLog=DEBUG

# Spring Framework \u00EB\u00A1\u009C\u00EA\u00B7\u00B8
logging.level.org.springframework=INFO
logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.security=DEBUG

# \u00EB\u008D\u00B0\u00EC\u009D\u00B4\u00ED\u0084\u00B0\u00EB\u00B2\u00A0\u00EC\u009D\u00B4\u00EC\u008A\u00A4 \u00EB\u00A1\u009C\u00EA\u00B7\u00B8
logging.level.org.hibernate=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

# Altibase \u00EB\u008D\u00B0\u00EC\u009D\u00B4\u00ED\u0084\u00B0\u00EB\u00B2\u00A0\u00EC\u009D\u00B4\u00EC\u008A\u00A4 \u00EC\u0084\u00A4\u00EC\u00A0\u0095
spring.datasource.altibase.jpa.read-only=false
spring.jpa.properties.hibernate.connection.read_only=false
spring.jpa.properties.hibernate.connection.provider_disables_autocommit=true
spring.datasource.altibase.jpa.default-transaction-isolation=2
spring.jpa.properties.hibernate.connection.isolation=2

# HTTP \u00ED\u0081\u00B4\u00EB\u009D\u00BC\u00EC\u009D\u00B4\u00EC\u0096\u00B8\u00ED\u008A\u00B8 \u00EB\u00A1\u009C\u00EA\u00B7\u00B8
logging.level.org.springframework.web.reactive.function.client=DEBUG
logging.level.reactor.netty.http.client=DEBUG

#==================================================================================================#
