package com.infra.mo.skt_giphttp_mo.dto.jna

object TraceDef {

    /* ERROR */
    const val ST_BALANCEQSEND_DATA_SIZE_WRONG =
        -100         /*DataSize오류*/                                        /*데이터사이즈*/
    const val ST_BALANCEQSEND_SEND_ACK_FAIL =
        -101         /*Ack실패*/                                             /*GetATCPMsg의 res*/
    const val ST_BALANCEQSEND_SEND_FAIL = -102         /*전송실패*/                                            /*없음*/
    const val ST_BALANCEQSEND_SOCK_RECV_FAIL =
        -103         /*소켓오류*/                                            /*GetATCPMsg의 res*/
    const val ST_CALLFW_DBL_FWD_TR = -104         /*DBLFWDTR*/                                    /*없음*/
    const val ST_CALLFW_DBL_FWD_TR2 = -105         /*DBLFWDTR*/                                    /*없음*/
    const val ST_CALLFW_DBL_FWD_TR3 = -106         /*DBLFWDTR*/                                    /*없음*/
    const val ST_CALLFW_DETECTED_CID = -107         /*착신전환 차단*/                                       /*CID*/
    const val ST_CALLFW_FTN_NOT_FOUND = -108         /* FTN 없음 2015.07.02 add NCHANGE ADD */
    const val ST_CALLFW_FWD_CNT_OVER = -109         /*착신전환횟수초과*/                    /*착신전환횟수=_pstQItem->ucRsv4Dlv[0]*/
    const val ST_CALLFW_INVALID_ESMCLASS = -110         /*잘못된ESMCLASS*/                              /*ESMCLASS*/
    const val ST_CALLFW_INVALID_ESM_CLASS =
        -111         /*잘못된 ESMCLASS*/                     /*ESMCLASS, ptrQItem->nRsv4Protocol[11]*/
    const val ST_CALLFW_INVALID_MSG_CODE =
        -112         /*잘못된MsgCode*/                                       /*MsgCode,MsgSubCode*/
    const val ST_CALLFW_INVALID_SRC_ADDR = -113         /*잘못된발신번호*/                                      /*발신번호*/
    const val ST_CALLFW_INVALID_TELECOM_NO = -114         /*잘못된TELECOMNO*/                             /*착신번호*/
    const val ST_DB_INS_FAIL_CALLINFO = -115         /*DB INS FAIL(CALLINFO)*/               /*DB 입력에 사용한 메시지 ID*/
    const val ST_DB_INS_FAIL_CALLINFO_3A = -116         /*DB INS FAIL(CALLINFO3A)*/             /*DB 입력에 사용한 메시지 ID*/
    const val ST_DB_INS_FAIL_FWDLINK_A_B_C = -117         /*DB INS FAIL(FWDLINK_ABC)*/    /*DB 입력에 사용한 메시지 ID*/
    const val ST_DB_INS_FAIL_GIPMOCALLINFO = -118         /*DB INS FAIL(GIPMOCAL)*/               /*DB 입력에 사용한 메시지 ID*/
    const val ST_DB_INS_FAIL_MOCALLINFO = -119         /*DB INS FAIL(MOCALLINFO)*/             /*DB 입력에 사용한 메시지 ID*/
    const val ST_DB_INS_FAIL_MONOTISEND = -120         /*DB INS FAIL(MONOTISE)*/               /*DB 입력에 사용한 메시지 ID*/
    const val ST_DB_INS_FAIL_MSGIDCONV = -121         /*DB INS FAIL(MSGIDCONV)*/              /*DB 입력에 사용한 메시지 ID*/
    const val ST_DB_INS_FAIL_PCSMTCALLINFO = -122         /*DB INS FAIL(PCSMTCAL)*/               /*DB 입력에 사용한 메시지 ID*/
    const val ST_DB_NO_DATA_CALLINFO = -123         /*DB NO DATA(CALLINFO)*/                /*DB 조회에 사용한 메시지 ID*/
    const val ST_DB_NO_DATA_FWDLINK_A_B_C = -124         /*DB NO DATA(FWDLINK_ABC)*/             /*DB 조회에 사용한 메시지 ID*/
    const val ST_DB_NO_DATA_GIPMOCALLINFO = -125         /*DB NO DATA(GIPMOCAL)*/                /*DB 조회에 사용한 메시지 ID*/
    const val ST_DB_NO_DATA_MOCALLINFO = -126         /*DB NO DATA(MOCALLINFO)*/              /*DB 조회에 사용한 메시지 ID*/
    const val ST_DB_NO_DATA_MONOTISEND = -127         /*DB NO DATA(MONOTISEND)*/              /*DB 조회에 사용한 메시지 ID*/
    const val ST_DB_NO_DATA_MO_CALL_NOTI = -128         /*NODATA(MO_CALL_NOTI)*/                /*DB 조회에 사용한 메시지 ID*/
    const val ST_DB_NO_DATA_MSGIDCONV = -129         /*DB NO DATA(MSGIDCONV)*/               /*DB 조회에 사용한 메시지 ID*/
    const val ST_DB_NO_DATA_PCSMTCALLINFO = -130         /*DB NO DATA(PCSMTCAL)*/                /*DB 조회에 사용한 메시지 ID*/
    const val ST_DB_SEL_FAIL_CALLINFO = -131         /*DB SEL FAIL(CALLINFO)*/               /*DB 조회에 사용한 메시지 ID*/
    const val ST_DB_SEL_FAIL_FWDLINK_A_B_C = -132         /*DB SEL FAIL(FWDLINK_ABC)*/    /*DB 조회에 사용한 메시지 ID*/
    const val ST_DB_SEL_FAIL_GIPMOCALLINFO = -133         /*DB SEL FAIL(GIPMOCAL)*/               /*DB 조회에 사용한 메시지 ID*/
    const val ST_DB_SEL_FAIL_MOCALLINFO = -134         /*DB SEL FAIL(MOCALLINFO)*/             /*DB 조회에 사용한 메시지 ID*/
    const val ST_DB_SEL_FAIL_MONOTISEND = -135         /*DB SEL FAIL(MONOTISEND)*/             /*DB 조회에 사용한 메시지 ID*/
    const val ST_DB_SEL_FAIL_MSGIDCONV = -136         /*DB SEL FAIL(MSGIDCONV)*/              /*DB 조회에 사용한 메시지 ID*/
    const val ST_DB_SEL_FAIL_PCSMTCALLINFO = -137         /*DB SEL FAIL(PCSMTCAL)*/               /*DB 조회에 사용한 메시지 ID*/
    const val ST_GIPEVENT_INVALID_DMIN = -138         /*잘못된 착신번호*/                                     /*착신 번호*/
    const val ST_GIPURL_INSQ_FAIL_ONCE_URL = -139         /*큐 입력 오류(ONCEURL)*/                       /*큐 번호*/
    const val ST_GIPURL_INVALID_SUBSCRIBER = -140         /*잘못된 가입자*/                                       /*착신 번호*/
    const val ST_GIPURL_ONCE_URL_AGREE_ERR = -141         /*Once URL 오류(Agree)*/                        /*착신 번호*/
    const val ST_GIPURL_ONCE_URL_ERR = -142         /*Once URL 오류*/                               /*착신 번호*/
    const val ST_GIP_FLOW_OVER = -143         /*Flow Count Over*/                             /*Flow Count 개수*/
    const val ST_GIP_INVALID_CID = -144         /*잘못된 CID*/                                  /*CID*/
    const val ST_GIP_INVALID_DATA_TYPE = -145         /*잘못된 DataType*/                             /*DataType*/
    const val ST_GIP_INVALID_DMIN =
        -146         /*잘못된 MIN NO*/                      /* dest minno */ /* dbpark 2012.11.15 */
    const val ST_GIP_INVALID_DMIN_010_NOSKT = -147         /*잘못된 착신번호(010)*/                        /*착신 번호*/
    const val ST_GIP_INVALID_DMIN_017_OFF = -148         /*잘못된 착신번호(017)*/                        /*착신 번호*/
    const val ST_GIP_INVALID_DMIN_AC_OFF = -149         /*잘못된 착신번호(ACOFF)*/                      /*착신 번호*/
    const val ST_GIP_INVALID_DMIN_AC_OFF_PORT = -150         /*잘못된 착신번호(ACOFF PORT)*/         /*착신 번호*/
    const val ST_GIP_INVALID_RGTDLV = -151         /*잘못된 RgtDlvFlag*/                           /*RgtDlvFlag*/
    const val ST_GIP_INVALID_SMIN_CMMANAGER = -152         /*잘못된 발신번호(Card 문자매니저)*/            /*발신 번호*/
    const val ST_GIP_INVALID_SMIN_SMSMANAGER = -153         /*잘못된 발신번호(문자매니저)*/         /*발신 번호*/
    const val ST_GIP_MORS_FAIL =
        -154         /*MO RES 실패*/                                 /*RES No : ptrMsgHdr->ucData[3]*/
    const val ST_GIP_MO_LIMIT = -155         /*MO 제한 번호*/                                        /*발신번호*/
    const val ST_GIP_MT_LIMIT = -156         /*MT 제한 번호*/                                        /*착신번호*/
    const val ST_GIP_MT_LIMIT_GIFT = -157         /*선물과금 제한 번호*/                          /*선물번호*/
    const val ST_GIP_SOCK_MAX_RETRY_FAIL = -158         /*소켓 MAX Retry 실패*/                 /*retry count*/
    const val ST_GIP_SOCK_SEND_BUF_FULL = -159         /*소켓 Send 버퍼 FULL*/                 /*retry count*/
    const val ST_GIP_SOCK_SEND_FAIL = -160         /*소켓 전송 실패*/                                      /*errno*/
    const val ST_GIP_SPAM_BLOCK = -161         /*Spam Block*/                                  /*Callback 번호*/
    const val ST_GSMSRECV_BILL_FAIL =
        -162         /*과금실패*/                                            /*nResult(nRsvProtocol[7])*/
    const val ST_GSMSRECV_FAILED_GET_QNO = -163         /*큐번호얻기실패*/                                      /*큐번호,발신번호*/
    const val ST_GSMSRECV_INVALID_DESTNO_010 = -164         /*잘못된010번호*/                                       /*착신번호*/
    const val ST_GSMSRECV_INVALID_DESTNO_01X = -165         /*잘못된타사번호*/                                      /*착신번호*/
    const val ST_GSMSRECV_INVALID_PREFIX =
        -166         /*잘못된PREFIX*/                                        /*큐번호,발신번호*/
    const val ST_GSMSRECV_INVALID_SUBSCRIBER_PORTED = -167         /*잘못된메시지형식*/                            /*착신번호*/
    const val ST_GSMSSEND_MORES_FAIL_FLOWOVER = -168         /*ACK실패(FLOWOVER,W2P)*/       /*Ack Result, SN*/
    const val ST_GSMSSEND_MORES_FAIL_FORMATERR = -169         /*ACK실패(FORMATERR,W2P)*/      /*Ack Result, SN*/
    const val ST_GSMSSEND_MORES_FAIL_SYSERR = -170         /*ACK실패(SYSFAIL,W2P)*/                /*Ack Result, SN*/
    const val ST_GSMSSEND_MOTR_NOT_SENT = -171         /*MOTR(전송실패)*/                      /*Rpt Result, SN*/
    const val ST_HBILLMO_GET_SRC_ADDR_FAIL =
        -172         /*SRC ADDR실패*/                                        /*발신 번호*/
    const val ST_HBILLMO_INVALID_MSGCODE = -173         /*잘못된메시지타입*/                            /*MsgCode, MsgSubCode*/
    const val ST_HBILLMO_NOT_BILL = -174         /*과금실패*/                                            /*MsgStatus*/
    const val ST_HBILLMO_SEL_FWDLINK_FAIL = -175         /*FWDLINK_ABC실패*/                             /*MsgId*/
    const val ST_HBILLMT_BILL_DONT_BILL = -176         /*과금실패*/                                            /*MsgStatus*/
    const val ST_NPDB_INVALID_CID = -177         /*잘못된CID*/                                           /*착신번호*/
    const val ST_NPDB_INVALID_DEST_SMSC = -178         /*잘못된SMSC*/                                  /*착신번호*/
    const val ST_NPDB_INVALID_DEST_SMSC_MO = -179         /*잘못된SMSC*/                                  /*착신번호*/
    const val ST_OTA_SOCK_SEND_FAIL = -180         /*OTA 전송 실패(MT)*/          /*ret(실패사유):sm_err_desc(ret,msg)*/
    const val ST_PCSIFRECV_FAILED_GET_QNO = -181         /*큐번호얻기실패*/                                      /*큐번호,발신번호*/
    const val ST_PCSIFRECV_FAILED_GET_QNO_PO = -182         /*큐번호얻기실패(PORTED)*/                      /*큐번호,발신번호*/
    const val ST_PCSIFRECV_FORMAT_INVALID = -183         /*잘못된발신번호*/                      /*발신번호*/
    const val ST_PCSIFRECV_INVALID_DESTNO_010 = -184         /*잘못된010번호*/                                       /*착신번호*/
    const val ST_PCSIFRECV_INVALID_DESTNO_01X = -185         /*잘못된타사번호*/                                      /*착신번호*/
    const val ST_PCSIFRECV_INVALID_MSGCODE = -186         /*잘못된메시지코드*/                            /*메시지코드*/
    const val ST_PCSIFRECV_SPAM_BLOCK = -187         /*스팸차단*/                                            /*발신번호*/
    const val ST_PCSIFRECV_SPAM_BLOCK_PO = -188         /*스팸차단(PORTED)*/                            /*발신번호*/
    const val ST_PCSIFRECV_SPAM_CB_BLOCK = -189         /*CALLBACK차단*/                                /*CALLBACK*/
    const val ST_PCSIFSEND_MORES_P2P_FAIL_FLOWOVER = -190         /*ACK실패(FLOWOVER,P2P)*/       /*Ack Result, SN*/
    const val ST_PCSIFSEND_MORES_P2P_FAIL_FORMATERR = -191         /*ACK실패(FORMATERR,P2P)*/      /*Ack Result, SN*/
    const val ST_PCSIFSEND_MORES_P2P_FAIL_NODESTIN = -192         /*ACK실패(E_NO_DESTIN)*/
    const val ST_PCSIFSEND_MORES_P2P_FAIL_SYSERR = -193         /*ACK실패(SYSFAIL,P2P)*/                /*Ack Result, SN*/
    const val ST_PCSIFSEND_MORES_W2P_FAIL_FLOWOVER = -194         /*ACK실패(FLOWOVER,W2P)*/       /*Ack Result, SN*/
    const val ST_PCSIFSEND_MORES_W2P_FAIL_FORMATERR = -195         /*ACK실패(FORMATERR,W2P)*/      /*Ack Result, SN*/
    const val ST_PCSIFSEND_MORES_W2P_FAIL_NODESTIN = -196         /*ACK실패(E_NO_DESTIN)*/
    const val ST_PCSIFSEND_MORES_W2P_FAIL_SYSERR = -197         /*ACK실패(SYSFAIL,W2P)*/                /*Ack Result, SN*/
    const val ST_PCSIFSEND_MOTR_P2P_NOT_SENT = -198         /*MOTR(전송실패,P2P)*/          /*Rpt Result, SN*/
    const val ST_PCSIFSEND_MOTR_W2P_NOT_SENT = -199         /*MOTR(전송실패,W2P)*/          /*Rpt Result, SN*/
    const val ST_Q_FULL = -200         /*큐 FULL*/                                             /*큐번호*/
    const val ST_Q_FULL_BALANCEQRECV = -201         /*큐 FULL*/                                             /*큐번호*/
    const val ST_Q_FULL_BLOCKNOTI = -202         /*큐 FULL(BLOCKNOTI)*/                  /*Queue 번호*/
    const val ST_Q_FULL_CALLFW = -203         /*큐 FULL(CALLFW)*/                             /*Queue 번호*/
    const val ST_Q_FULL_CALLFW_SKT_FWD_MT = -204         /*큐 FULL(SKT착신전환)*/                        /*큐번호*/
    const val ST_Q_FULL_CMMANAGER = -205         /*큐 FULL(Card 문자매니저)*/
    const val ST_Q_FULL_GIP_MO = -206         /*큐 FULL(GIPMO)*/                              /*Queue 번호*/
    const val ST_Q_FULL_GIP_TR = -207         /*큐 FULL(GIP)*/                                        /*Queue 번호*/
    const val ST_Q_FULL_GIP_TR_DBLFWD = -208         /*큐 FULL(DBLFWTR)*/                            /*Queue 번호*/
    const val ST_Q_FULL_GLOBALRECV_MT = -209         /*큐 FULL(SMSC)*/                               /*큐번호*/
    const val ST_Q_FULL_GLOBALSEND_FAILNOTI_MT = -210         /*큐 FULL(SMSC)*/                               /*큐번호*/
    const val ST_Q_FULL_GSMSRECV_MT = -211         /*큐 FULL(SMSC)*/                               /*큐번호*/
    const val ST_Q_FULL_GSMSSEND_FAILNOTI_MT = -212         /*큐 FULL(SMSC)*/                               /*큐번호*/
    const val ST_Q_FULL_HBILLMO_NOTIPLUS_MT = -213         /*큐 FULL(안심)*/                                       /*큐번호*/
    const val ST_Q_FULL_HBILLMO_NOTISEND_MT = -214         /*큐 FULL(등기)*/                                       /*큐번호*/
    const val ST_Q_FULL_HBILLMO_PCSRECV_TR = -215         /*큐 FULL(TR)*/                                 /*큐번호*/
    const val ST_Q_FULL_NOTISEND_MT = -216         /*큐 FULL(등기)*/                               /*큐번호*/
    const val ST_Q_FULL_NPDB = -217         /*큐 FULL(NPDB)*/                               /*Queue 번호*/
    const val ST_Q_FULL_NPDB_SKT_FWDMO = -218         /*큐 FULL(SKT착신전환)*/                        /*큐번호*/
    const val ST_Q_FULL_PCSIFRECV_MT = -219         /*큐 FULL(SMSC)*/                               /*큐번호*/
    const val ST_Q_FULL_PCSIFRECV_MT_PO = -220         /*큐 FULL(SMSC,PO)*/                            /*큐번호*/
    const val ST_Q_FULL_PCSIFRECV_TR = -221         /*큐 FULL(HBILLMT)*/                            /*큐번호*/
    const val ST_Q_FULL_PCSIFSEND_TR_P2P = -222         /*큐 FULL(P2P,HBILLMO)*/                        /*큐번호*/
    const val ST_Q_FULL_PCSIFSEND_TR_P2P_ETC = -223         /*큐 FULL(P2P,HBILLMO)*/                        /*큐번호*/
    const val ST_Q_FULL_PCSIFSEND_TR_P2P_PO = -224         /*큐 FULL(P2P,NPDB)*/                   /*큐번호*/
    const val ST_Q_FULL_PCSIFSEND_TR_W2P = -225         /*큐 FULL(W2P,VSMSSTR)*/                        /*큐번호*/
    const val ST_Q_FULL_POLL = -226         /*큐 FULL(POLL)*/                               /*Queue 번호*/
    const val ST_Q_FULL_SMSC = -227         /*큐 FULL(SMSC)*/                               /*Queue 번호*/
    const val ST_Q_FULL_SMSMANAGER = -228         /*큐 FULL(문자매니저)*/                 /*SP Code*/
    const val ST_Q_FULL_SMSMOR_MO_NCON_MO = -229         /*큐 FULL(MO,NCON,MO)*/                 /*큐번호*/
    const val ST_Q_FULL_SMSMOR_MO_NCON_PO = -230         /*큐 FULL(MO,NCON,PORTED)*/             /*큐번호*/
    const val ST_Q_FULL_SMSMOR_MO_NCON_TR = -231         /*큐 FULL(MO,NCON,TR)*/                 /*큐번호*/
    const val ST_Q_FULL_SMSMOR_MO_NORMAL = -232         /*큐 FULL(MO,NORMAL)*/                  /*큐번호*/
    const val ST_Q_FULL_SMSMOR_TR_NCON_MO = -233         /*큐 FULL(TR,NCON,MO)*/                 /*큐번호*/
    const val ST_Q_FULL_SMSMOR_TR_NCON_PO = -234         /*큐 FULL(TR,NCON,PORTED)*/             /*큐번호*/
    const val ST_Q_FULL_SMSMOR_TR_NCON_TR = -235         /*큐 FULL(TR,NCON,TR)*/                 /*큐번호*/
    const val ST_Q_FULL_SMSMOR_TR_NILCOM1 = -236         /*큐 FULL(TR,NILCOM1)*/                 /*큐번호*/
    const val ST_Q_FULL_SMSMOR_TR_NILCOM2 = -237         /*큐 FULL(TR,NILCOM2)*/                 /*큐번호*/
    const val ST_Q_FULL_SMSMOR_TR_NORMAL = -238         /*큐 FULL(TR,NORMAL)*/                  /*큐번호*/
    const val ST_Q_FULL_SMSMOR_TR_NPDBQ = -239         /*큐 FULL(TR,NPDB)*/                            /*큐번호*/
    const val ST_Q_FULL_SMSMOR_TR_WLONG = -240         /*큐 FULL(TR,WLONG)*/                   /*큐번호*/
    const val ST_Q_FULL_TRANSEND = -241         /*큐 FULL(TRANSEND)*/                   /*Queue 번호*/
    const val ST_Q_FULL_VBILL = -242         /*큐 FULL(VBILL)*/                              /*Queue 번호*/
    const val ST_Q_FULL_VBILLMO = -243         /*큐 FULL(VBILLMO)*/                            /*Queue 번호*/
    const val ST_Q_FULL_VMRMSEND = -244         /*큐 FULL(VMRMSEND)*/                   /*Queue 번호*/
    const val ST_Q_HMRMSEND_TR_ERROR = -245
    const val ST_Q_INSERT_FAIL = -246         /*큐 입력 오류*/                                        /*큐번호*/
    const val ST_Q_INSERT_FAIL_BALANCEQRECV = -247         /*큐 입력 오류*/                                        /*큐번호*/
    const val ST_Q_INSERT_FAIL_BLOCKNOTI = -248         /*큐 입력 오류(BLOCKNOTI)*/             /*Queue 번호*/
    const val ST_Q_INSERT_FAIL_CALLFW = -249         /*큐 입력 오류(CALLFW)*/                        /*Queue 번호*/
    const val ST_Q_INSERT_FAIL_CALLFW_H2H_KTF_FWD_MO = -250         /*큐 입력 오류(KTF착신전환,H2H)*/       /*큐번호*/
    const val ST_Q_INSERT_FAIL_CALLFW_H2H_LGT_FWD_MO = -251         /*큐 입력 오류(LGT착신전환,H2H)*/       /*큐번호*/
    const val ST_Q_INSERT_FAIL_CALLFW_KTF_FWD_MO = -252         /*큐 입력 오류(KTF착신전환)*/           /*큐번호*/
    const val ST_Q_INSERT_FAIL_CALLFW_LGT_FWD_MO = -253         /*큐 입력 오류(LGT착신전환)*/           /*큐번호*/
    const val ST_Q_INSERT_FAIL_CALLFW_PCS_TR = -254         /*큐 입력 오류(타사TR)*/                        /*큐번호*/
    const val ST_Q_INSERT_FAIL_CALLFW_PCS_TR2 = -255         /*큐 입력 오류(타사TR)*/                        /*큐번호*/
    const val ST_Q_INSERT_FAIL_CALLFW_RECV_Q = -256         /*큐 입력 오류(RECVQ)*/                 /*큐번호*/
    const val ST_Q_INSERT_FAIL_CALLFW_SKT_FWD_MT = -257         /*큐 입력 오류(SKT착신전환)*/           /*큐번호*/
    const val ST_Q_INSERT_FAIL_CMMANAGER = -258         /*큐 입력 오류(Card 문자매니저)*/
    const val ST_Q_INSERT_FAIL_GIP_MO = -259         /*큐 입력 오류(GIPMO)*/                 /*Queue 번호*/
    const val ST_Q_INSERT_FAIL_GIP_TR = -260         /*큐 입력 오류(GIPTR)*/                 /*Queue 번호*/
    const val ST_Q_INSERT_FAIL_GIP_TR_DBLFWD = -261         /*큐 입력 오류(DBLFWTR)*/                       /*Queue 번호*/
    const val ST_Q_INSERT_FAIL_GLOBALRECV_MT = -262         /*큐 입력 오류(SMSC)*/                          /*큐번호*/
    const val ST_Q_INSERT_FAIL_GLOBALSEND_FAILNOTI_MT = -263         /*큐 입력 오류(FAILNOTI)*/                      /*큐번호*/
    const val ST_Q_INSERT_FAIL_GLOBALSEND_GWEB_TR = -264         /*큐 입력 오류(GWEB_TR)*/                       /*큐번호*/
    const val ST_Q_INSERT_FAIL_GLOBALSEND_NPDB = -265         /*큐 입력 오류(NPDB)*/                          /*큐번호*/
    const val ST_Q_INSERT_FAIL_GSMSRECV_MT = -266         /*큐 입력 오류(SMSC)*/                          /*큐번호*/
    const val ST_Q_INSERT_FAIL_GSMSSEND_FAILNOTI_MT = -267         /*큐 입력 오류(FAILNOTI)*/                      /*큐번호*/
    const val ST_Q_INSERT_FAIL_GSMSSEND_GWEB_TR = -268         /*큐 입력 오류(GWEB_TR)*/                       /*큐번호*/
    const val ST_Q_INSERT_FAIL_GSMSSEND_NPDB = -269         /*큐 입력 오류(NPDB)*/                          /*큐번호*/
    const val ST_Q_INSERT_FAIL_GWEB_MT = -270         /*큐 입력 오류(FAILNOTI)*/                      /*큐번호*/
    const val ST_Q_INSERT_FAIL_H2HIFRECV_MO = -271         /*큐 입력 오류*/                                        /*큐번호*/
    const val ST_Q_INSERT_FAIL_H2HIFSEND_TR = -272         /*큐입력실패*/                          /*큐번호*/
    const val ST_Q_INSERT_FAIL_HBILLMO_H2H_TR = -273         /*큐 입력 오류(TR)*/                            /*큐번호*/
    const val ST_Q_INSERT_FAIL_HBILLMO_NOTIPLUS_MT = -274         /*큐 입력 오류(안심)*/                          /*큐번호*/
    const val ST_Q_INSERT_FAIL_HBILLMO_NOTISEND_MT = -275         /*큐 입력 오류(등기)*/                          /*큐번호*/
    const val ST_Q_INSERT_FAIL_HBILLMO_PCSRECV_TR = -276         /*큐 입력 오류(TR)*/                            /*큐번호*/
    const val ST_Q_INSERT_FAIL_HMRMRECV_MO = -277         /*큐 입력 오류*/                                        /*큐번호*/
    const val ST_Q_INSERT_FAIL_NOTISEND_MT = -278         /*큐 입력 오류(등기)*/                  /*큐번호*/
    const val ST_Q_INSERT_FAIL_NPDB = -279         /*큐 입력 오류(NPDB)*/                          /*Queue 번호*/
    const val ST_Q_INSERT_FAIL_NPDB_DBLFWDTR = -280         /*큐 입력 오류(DBLFWDTR)*/                      /*큐번호*/
    const val ST_Q_INSERT_FAIL_NPDB_FWD = -281         /*큐 입력 오류(착신전환)*/                      /*큐번호*/
    const val ST_Q_INSERT_FAIL_NPDB_FWD_ACK_FAIL = -282         /*큐 입력 오류(착신전환)*/                      /*큐번호*/
    const val ST_Q_INSERT_FAIL_NPDB_MO = -283         /*큐 입력 오류(MO)*/                            /*큐번호*/
    const val ST_Q_INSERT_FAIL_NPDB_PBILL = -284         /*큐 입력 오류(PBILL)*/                 /*큐번호*/
    const val ST_Q_INSERT_FAIL_NPDB_PORTEDMO = -285         /*큐 입력 오류(PORTEDMO)*/                      /*큐번호*/
    const val ST_Q_INSERT_FAIL_NPDB_SKT_FWDMO = -286         /*큐 입력 오류(SKT착신전환)*/           /*큐번호*/
    const val ST_Q_INSERT_FAIL_NPDB_SKT_MT = -287         /*큐 입력 오류(SKT착신전환)*/           /*큐번호*/
    const val ST_Q_INSERT_FAIL_PCSIFRECV_MT = -288         /*큐 입력 오류(SMSC)*/                          /*큐번호*/
    const val ST_Q_INSERT_FAIL_PCSIFRECV_MT_PO = -289         /*큐 입력 오류(SMSC,PO)*/                       /*큐번호*/
    const val ST_Q_INSERT_FAIL_PCSIFRECV_TR = -290         /*큐 입력 오류(HBILLMT)*/                       /*큐번호*/
    const val ST_Q_INSERT_FAIL_PCSIFSEND_TR_P2P = -291         /*큐 입력 오류(P2P,HBILLMO)*/           /*큐번호*/
    const val ST_Q_INSERT_FAIL_PCSIFSEND_TR_P2P_ETC = -292         /*큐 입력 오류(P2P,HBILLMO)*/           /*큐번호*/
    const val ST_Q_INSERT_FAIL_PCSIFSEND_TR_P2P_PO = -293         /*큐 입력 오류(P2P,NPDB)*/                      /*큐번호*/
    const val ST_Q_INSERT_FAIL_PCSIFSEND_TR_W2P = -294         /*큐 입력 오류(W2P,VSMSSTR)*/           /*큐번호*/
    const val ST_Q_INSERT_FAIL_PMIFRECV_MO = -295         /*큐 입력 오류*/                                        /*큐번호*/
    const val ST_Q_INSERT_FAIL_PMIFRECV_NORMAL_MO_KTF = -296         /*큐 입력 오류(NORMAL,KTF)*/            /*큐번호*/
    const val ST_Q_INSERT_FAIL_PMIFRECV_NORMAL_MO_LGT = -297         /*큐 입력 오류(NORMAL,KTF)*/            /*큐번호*/
    const val ST_Q_INSERT_FAIL_PMIFRECV_PO_MO = -298         /*큐 입력 오류(PORTED)*/                        /*큐번호*/
    const val ST_Q_INSERT_FAIL_POLL = -299         /*큐 입력 오류(POLL)*/                          /*Queue 번호*/
    const val ST_Q_INSERT_FAIL_SMSC = -300         /*큐 입력 오류(SMSC)*/                          /*Queue 번호*/
    const val ST_Q_INSERT_FAIL_SMSMANAGER = -301         /*큐 입력 오류(문자매니저)*/                    /*SP Code*/
    const val ST_Q_INSERT_FAIL_SMSMOR_MO_NCON_MO = -302         /*큐 입력 오류(MO,NCON,MO)*/            /*큐번호*/
    const val ST_Q_INSERT_FAIL_SMSMOR_MO_NCON_PO = -303         /*큐 입력 오류(MO,NCON,PORTED)*/        /*큐번호*/
    const val ST_Q_INSERT_FAIL_SMSMOR_MO_NCON_TR = -304         /*큐 입력 오류(MO,NCON,TR)*/            /*큐번호*/
    const val ST_Q_INSERT_FAIL_SMSMOR_MO_NORMAL = -305         /*큐 입력 오류(MO,NORMAL)*/             /*큐번호*/
    const val ST_Q_INSERT_FAIL_SMSMOR_TR_NCON_MO = -306         /*큐 입력 오류(TR,NCON,MO)*/            /*큐번호*/
    const val ST_Q_INSERT_FAIL_SMSMOR_TR_NCON_PO = -307         /*큐 입력 오류(TR,NCON,PORTED)*/        /*큐번호*/
    const val ST_Q_INSERT_FAIL_SMSMOR_TR_NCON_TR = -308         /*큐 입력 오류(TR,NCON,TR)*/            /*큐번호*/
    const val ST_Q_INSERT_FAIL_SMSMOR_TR_NILCOM1 = -309         /*큐 입력 오류(TR,NILCOM1)*/            /*큐번호*/
    const val ST_Q_INSERT_FAIL_SMSMOR_TR_NILCOM2 = -310         /*큐 입력 오류(TR,NILCOM2)*/            /*큐번호*/
    const val ST_Q_INSERT_FAIL_SMSMOR_TR_NORMAL = -311         /*큐 입력 오류(TR,NORMAL)*/             /*큐번호*/
    const val ST_Q_INSERT_FAIL_SMSMOR_TR_NPDBQ = -312         /*큐 입력 오류(TR,NPDB)*/                       /*큐번호*/
    const val ST_Q_INSERT_FAIL_SMSMOR_TR_WLONG = -313         /*큐 입력 오류(WLONG)*/                 /*큐번호*/
    const val ST_Q_INSERT_FAIL_TRANSEND = -314         /*큐 입력 오류(TRANSEND)*/                      /*Queue 번호*/
    const val ST_Q_INSERT_FAIL_VBILL = -315         /*큐 입력 오류(VBILL)*/                 /*Queue 번호*/
    const val ST_Q_INSERT_FAIL_VBILLMO = -316         /*큐 입력 오류(VBILLMO)*/                       /*Queue 번호*/
    const val ST_Q_INSERT_FAIL_VMRMSEND = -317         /*큐 입력 오류(VMRMSEND)*/                      /*Queue 번호*/
    const val ST_Q_INSERT_FAIL_VSMSSTR_TR = -318         /*큐 입력 오류(TR)*/                            /*큐번호*/
    const val ST_Q_SMSMOR_ALTINODATA_MO_NCON_MO = -319         /*DB NODATA(NCON,MO)*/                  /*큐번호*/
    const val ST_Q_SMSMOR_ALTINODATA_MO_NCON_PO = -320         /*DB NODATA(NCON,PORTED)*/              /*큐번호*/
    const val ST_Q_SMSMOR_ALTINODATA_MO_NCON_TR = -321         /*DB NODATA(NCON,TR)*/                  /*큐번호*/
    const val ST_Q_SMSMOR_ALTINODATA_MO_NORMAL = -322         /*DB NODATA(MO,NORMAL)*/                /*큐번호*/
    const val ST_Q_SMSMOR_ALTINODATA_TR_NCON_MO = -323         /*DB NODATA(TR,NCON,MO)*/               /*큐번호*/
    const val ST_Q_SMSMOR_ALTINODATA_TR_NCON_PO = -324         /*DB NODATA(TR,NCON,PORTED)*/   /*큐번호*/
    const val ST_Q_SMSMOR_ALTINODATA_TR_NCON_TR = -325         /*DB NODATA(TR,NCON,TR)*/               /*큐번호*/
    const val ST_Q_SMSMOR_ALTINODATA_TR_NORMAL = -326         /*DB NODATA(TR,NORMAL)*/                /*큐번호*/
    const val ST_SMSMOR_INVALID_DATA = -327         /*잘못된 데이터포맷(MO)*/                       /*착신 번호*/
    const val ST_SMSMOR_INVALID_DMIN = -328         /*잘못된 착신번호(TR)*/                         /*착신 번호*/
    const val ST_SMSMOR_INVALID_DMIN_TR = -329         /*잘못된 착신번호(TR)*/                         /*메시지 ID, 착신 번호*/
    const val ST_SMSMOR_TR_ADMCANC = -330         /* DIS_ADMIN_BAR(TR) */
    const val ST_SMSMOR_TR_FWDFAIL = -332         /* FWD_2_FAIL(TR) */
    const val ST_SMSMOR_TR_NPREFIX = -333         /* NO_PREFIX_INFO(TR) */
    const val ST_SMSMOR_TR_SEND = -331         /* SEND_OK(TR) */                    /* C 코드 기준: msgStatus==2 */
    const val ST_SMSMOR_TR_PORTOUT = -334         /* PORTOUT(TR) */
    const val ST_SMSMOR_TR_SPAMERR = -335         /* SPAM_BLOCK(TR) */
    const val ST_SMSMOR_TR_UNDELIVERED =
        -336         /*UNDELIVERED(TR)*/                  /*메시지 ID, Status:stQItem.ucMsgStatus*/
    const val ST_SMSMOR_TR_USERDEL = -337         /* USER_DELETE(TR) */
    const val ST_SMSMOR_WLONG_ESM =
        -338         /*WLONG TR 수신*/                       /*ESM_CLASS(QItem.nRsv4Protocol[11])*/
    const val ST_SMSMOR_WLONG_FWD_CNT_OVER =
        -339         /*착신전환횟수초과(WLONG)*/             /*착신전환횟수(stQItem.ucRsv4Dlv[0])*/
    const val ST_SMSMOT_INVALID_TID =
        -340         /*잘못된 TID(MT)*/                              /*TID:ptrQItem->usMsgCodeReserved[0]*/
    const val ST_SMSMOT_SOCK_SEND_FAIL =
        -341         /*SMSC 전송 실패(MT)*/                  /*ret(실패사유):sm_err_desc(ret,msg)*/
    const val ST_SMSMOT_UNKNOWN_QTYPE =
        -342         /*UNKNOWN QTYPE(MT)*/                   /*ptrQItem->usMsgCode(QueueType)*/
    const val ST_TRECV_DATA_SIZE_WRONG = -343         /*DATA SIZE WRONG*/                             /*data size*/
    const val ST_TRECV_SEND_ACK_FAIL =
        -344         /*ACK 전송실패*/                                        /*메시지ID:stQItem.ucMsgId*/
    const val ST_TSEND_SEND_DATA_FAIL = -345         /*DATA 전송실패*/                                       /*errno*/
    const val ST_VBILLMO_SUCC_NOTISEND = 137         /*성공안심문자*/                                      /*안심문자과금성공*/
    const val ST_VBILLMO_INSQ_NOTISEND = 139    /*안심문자전송*/
    const val ST_VBILLMO_OK = 141         /*과금성공*/                                      /*VBILL_MO 과금 성공*/
    const val ST_VBILLMO_NOTISEND_OK =
        142         /*성공(MONOTISEND)*/                          /*VBILL_MO 성공 (MO_NOTISEND)*/
    const val ST_VBILLMO_DONT_BILL_TRFAIL =
        -346         /*과금실패(TRFAIL)*/                            /*TRStatus:ptrQitem->ucMsgStatus*/
    const val ST_VBILLMO_INVALID_CID = -347         /*잘못된 CID*/                                  /*발신CID*/
    const val ST_VRECV_DATA_SIZE_WRONG = -348         /*DATA SIZE WRONG*/                             /*data size*/
    const val ST_VRECV_TR_EXPIRED =
        -349         /*EXPIRED(HSMSS TR)*/                   /*메시지 ID, Status:stQItem.ucMsgStatus*/
    const val ST_VRECV_TR_UNDELIVERED =
        -350         /*UNDELIVERED(HSMSS TR)*/               /*메시지 ID, Status:stQItem.ucMsgStatus*/
    const val ST_VSEND_SEND_DATA_FAIL = -351         /*DATA 전송실패*/
    const val ST_GLOBALRECV_INVALID_MSGCODE = -352         /*잘못된메시지코드*/                /*메시지코드*/
    const val ST_GLOBALRECV_INVALID_DESTNO_010 = -353         /*잘못된010번호*/                   /*착신번호*/
    const val ST_GLOBALRECV_INVALID_DESTNO_01X = -354         /*잘못된타사번호*/                  /*착신번호*/
    const val ST_GLOBALRECV_FAILED_GET_QNO = -355         /*큐번호얻기실패*/                  /*큐번호,발신번호*/
    const val ST_GLOBALRECV_BILL_FAIL = -356         /*과금실패*/                        /*nResult(nRsvProtocol[7])*/
    const val ST_GLOBALRECV_FORMAT_INVALID_PORTED = -357         /*잘못된메시지형식*/                /*착신번호*/
    const val ST_GLOBALRECV_EXPIRED = -358         /*전송 실패*//*Bright Modify 2011 03.28 GLOABAL RECV ERROR CODE ADD*/
    const val ST_Q_FULL_HBILLMO_H2H_TR = -359         /*큐 FULL(TR)*//*큐번호*/
    const val ST_Q_FULL_H2HIFRECV_MO = -360         /*큐 FULL(안심문자)*//*큐번호*/
    const val ST_Q_FULL_GWEB_MT = -361         /*큐 FULL(SMSC)*//*큐번호*/
    const val ST_PMIFRECV_INVALID_RD_VALUE = -362         /*잘못된Source큐*//*ptrQItem->usSource*/
    const val ST_PMIFRECV_NOT_ALLOW_SKT_DEST = -363         /*잘못된 DEST(SKT)*//*착신번호ptrQItem->szMinNo*/
    const val ST_PMIFRECV_INVALID_010_ADDR = -364         /*잘못된 010 Prefix*//*착신번호*/
    const val ST_H2HIFRECV_INVALID_010_ADDR = -365         /*잘못된 010 Prefix*//*착신번호*/
    const val ST_GLOBALSEND_MORES_FAIL_SYSERR = -366         /*ACK실패(SYSFAIL,W2P)*//*Ack Result, SN*/
    const val ST_GLOBALSEND_MORES_FAIL_FLOWOVER = -367         /*ACK실패(FLOWOVER,W2P)*//*Ack Result, SN*/
    const val ST_GLOBALSEND_MORES_FAIL_FORMATERR = -368         /*ACK실패(FORMATERR,W2P)*//*Ack Result, SN*/
    const val ST_GLOBALSEND_MOTR_NOT_SENT = -369         /*MOTR(전송실패)*//*Rpt Result, SN*/
    const val ST_GWEB_MT_TR_NOT_SENT = -370         /*MOTR(전송실패)*//*ptrQItem->ucMsgStatus*/
    const val ST_GWEB_INVALID_DEST_SMSC = -371         /*잘못된DESTSMSC*//*착신번호*/
    const val ST_SMSMOR_TR_FORWARD = -372         /*FORWARD(TR)*/
    const val ST_Q_INSERT_FAIL_OCS = -373        /* OCS->NPDB InsertQ Fail */
    const val ST_SMSMOR_MO_INSQ_OK = 114         /*성공 (MO Q삽입)*/                  /*큐 번호*/
}